version: '3.8'
services:
  postgres:
    build:
      context: ./db
      dockerfile: postgres_dockerfile
      args:
        - PG_REPO=https://github.com/postgrespro/postgres.git
        - PG_BRANCH=jsonb_toaster # PG_BRANCH=REL_17_STABLE
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./app
      dockerfile: service_dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=postgres
      - DATABASE_URL=postgres://postgres:pass@postgres:5432/postgres?sslmode=disable

  loadgen:
    build:
      context: ./workload
      dockerfile: workloader_dockerfile
    depends_on:
      - app
      - postgres
    ports:
      - "8090:8090"  # порт для API динамического обновления конфигурации loadgen
    environment:
      - MAIN_SERVICE_URL=http://app:8080
    restart: on-failure

volumes:
  db_data:
  monitor_data: